import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[shell]
program="tmux"

[font]
normal = { family = "NotoMono Nerd Font", style = "Regular" }
bold = { family = "NotoMono Nerd Font", style = "Bold" }
italic = { family = "NotoMono Nerd Font", style = "Italic" }
bold_italic = { family = "NotoMono Nerd Font", style = "Bold Italic" }
size = 11.25
